language: python
python:
  - '3.6'
notifications:
  email: false
before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get update
  - bash .travis/install_conda.sh
install: "pip install -r requirements.txt"
script: make travis
after_script:
  - echo "Rendered notebook http://nbviewer.jupyter.org/urls/s3.amazonaws.com/pythonplotbuilds/tdhopper/pythonplot.com/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/Examples.$(git log -1 --pretty=format:'%h').ipynb"
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./web
  skip_cleanup: true
  on:
    branch: netlify